# Automation Team - Jabil Belo
# Agosto de 2019
# v1.2

version: '2'
services:
  BLE:
    image: beacon-gateway:legacy
    privileged: true
    tty: true
    dns_search: corp.jabil.org
    environment:
      - APP_HOST=${APP_HOST}
      - APP_PORT=${APP_PORT}
      - NODE_ENV=${NODE_ENV}
      - MQTT_BROKER=${MQTT_BROKER}
      - MQTT_PORT=${MQTT_PORT}
      - MQTT_TOPIC=${MQTT_TOPIC}
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASS=${MQTT_PASS}
    network_mode: host
    volumes:
      - /etc/hostname:/etc/hostname
    # devices:
    #   - "/dev/ttyUSB0:/dev/ttyACM0"
    

      
