# Automation Team - Jabil Belo
# Agosto de 2019
# v1.2

version: '2'
services:
  BLE:
    image: docker.corp.jabil.org/automation-bel/beacon-gateway:legacy
    privileged: true
    tty: true
    dns_search: corp.jabil.org
    environment:
      - MQTT_BROKER=${MQTT_BROKER}
      - MQTT_PORT=${MQTT_PORT}
      - MQTT_TOPIC=${MQTT_TOPIC}
      - SCAN_MODE=${SCAN_MODE}
    network_mode: host
    volumes:
      - /etc/hostname:/etc/hostname
    # devices:
    #   - "/dev/ttyUSB0:/dev/ttyACM0"
    

      
