version: '2'
services:
  BLE:
    image: beacon-scanner
    privileged: true
    tty: true
    network_mode: host
    volumes:
      - /etc/hostname:/etc/hostname
    environment:
      - MQTT_BROKER=broker.emqx.io
      - MQTT_PORT=1883
      - MQTT_TOPIC=aoliveira/rtls

      
